apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::424108484860:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::424108484860:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CEJOS06OY2NU
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-28T16:56:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1699"
  uid: 5b61ac0d-a366-4f48-8b17-d520205e8242
